services:
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # Локальный доступ к БД
    volumes:
      - postgres_data:/var/lib/postgresql/data


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres_data:
